// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    ellipsis: string
    ol: string
    time: string
}
export const cssExports: CssExports
export default cssExports
