// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    "client-box": string
    "client-content": string
    "client-left": string
    "client-right": string
    clientBox: string
    clientContent: string
    clientLeft: string
    clientRight: string
}
export const cssExports: CssExports
export default cssExports
