// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    "hitokoto-box": string
    "hitokoto-from": string
    "hitokoto-value": string
    hitokotoBox: string
    hitokotoFrom: string
    hitokotoValue: string
}
export const cssExports: CssExports
export default cssExports
