// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    "beian-info": string
    beianInfo: string
    "footer-content": string
    footerContent: string
    gongan: string
    icp: string
    "page-copyright": string
    "page-footer": string
    pageCopyright: string
    pageFooter: string
    "social-info": string
    "social-media": string
    socialInfo: string
    socialMedia: string
}
export const cssExports: CssExports
export default cssExports
