// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    ellipsis: string
    list: string
    rate: string
}
export const cssExports: CssExports
export default cssExports
